name: Push to Space

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: '0.0.1'
      note:
          description: '发布说明'
          required: true
          default: '更新'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: lizheming/deta-action@master
        with:
          access_token: ${{ secrets.SPACE_ACCESS_TOKEN }}
          id: ${{ secrets.SPACE_PROJECT_ID }}
          version: ${{ github.event.inputs.tag}}
          notes: ${{ github.event.inputs.note}}
          listed: true
