name: Push to Space

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: 'v0.0.3'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: lizheming/deta-action@master
        with:
          access_token: ${{ secrets.SPACE_ACCESS_TOKEN }}
          id: ${{ secrets.SPACE_PROJECT_ID }}
          version: "1.0.0"
          notes: "更新"
          listed: true
